version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: crowdfund
      POSTGRES_PASSWORD: Crowd.Fund
      POSTGRES_DB: crowdfund_db
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://crowdfund:Crowd.Fund@db:5432/crowdfund_db"
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

networks:
  backend:

volumes:
  postgres_data:
