"""contribution model changed

Revision ID: a6de7a0bed8e
Revises: b7a5346bdcfa
Create Date: 2025-01-17 06:17:33.638209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6de7a0bed8e'
down_revision: Union[str, None] = 'b7a5346bdcfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contribution', sa.Column('creator_id', sa.UUID(), nullable=False))
    op.alter_column('Contribution', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('Contribution_user_id_fkey', 'Contribution', type_='foreignkey')
    op.create_foreign_key(None, 'Contribution', 'User', ['creator_id'], ['id'])
    op.drop_column('Contribution', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contribution', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Contribution', type_='foreignkey')
    op.create_foreign_key('Contribution_user_id_fkey', 'Contribution', 'User', ['user_id'], ['id'])
    op.alter_column('Contribution', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('Contribution', 'creator_id')
    # ### end Alembic commands ###
