"""contribution model modified

Revision ID: a864afa6d964
Revises: 33df79fca9f3
Create Date: 2025-01-17 12:22:24.623008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a864afa6d964'
down_revision: Union[str, None] = '33df79fca9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contribution', sa.Column('contributor_id', sa.UUID(), nullable=False))
    op.drop_constraint('Contribution_creator_id_fkey', 'Contribution', type_='foreignkey')
    op.create_foreign_key(None, 'Contribution', 'User', ['contributor_id'], ['id'])
    op.drop_column('Contribution', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contribution', sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Contribution', type_='foreignkey')
    op.create_foreign_key('Contribution_creator_id_fkey', 'Contribution', 'User', ['creator_id'], ['id'])
    op.drop_column('Contribution', 'contributor_id')
    # ### end Alembic commands ###
